version: "3.7"

services:
  unit-test:
    container_name: small-class-manipulator-unit-test
    build:
      context: .
      args:
        - BUILD=1 # If set to 0, container will sleep to let you run all tests commands you want when you develop tests
    volumes:
      - .:/usr/lib/small-class-manipulator